<?xml version="1.0"?>
<robot name="andrzej" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find andrzej_description)/urdf/andrzej_arms_spec.xacro" />
  
  <xacro:macro name="arm_base" params="arm_name reflect">
    <link name="arm_${arm_name}_link_0">
      <visual>
        <geometry>
          <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
        </geometry>
        <material name="orange"/>
      </visual>
      <collision>
        <geometry>
          <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="${arm_base_mass}"/>
    </link>
    
    <joint name="platform_to_arm_${arm_name}" type="fixed">
      <parent link="base_link"/>
      <child link="arm_${arm_name}_link_0"/>
      <origin xyz="${base_length*reflect/4} 0 ${(base_height+arm_base_height)/2}"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="arm_link" params="arm_name link_name">
    <link name="arm_${arm_name}_link_${link_name}">
      <visual>
        <xacro:call macro="arm_${arm_name}_link_${link_name}_visual"/>
      </visual>
    </link>

    <joint name="arm_${arm_name}_joint_${link_name}" type="revolute">
      <xacro:call macro="arm_${arm_name}_joint_${link_name}_spec"/>
      <parent link="arm_${arm_name}_link_${link_name-1}"/>
      <child link="arm_${arm_name}_link_${link_name}"/>
    </joint>      
  </xacro:macro>

  <xacro:macro name="arm" params="arm_name">
    <xacro:arm_link arm_name="${arm_name}" link_name="1"/>
    <xacro:arm_link arm_name="${arm_name}" link_name="2"/>
    <xacro:arm_link arm_name="${arm_name}" link_name="3"/>
    <xacro:arm_link arm_name="${arm_name}" link_name="4"/>
    <xacro:arm_link arm_name="${arm_name}" link_name="5"/>
  </xacro:macro>
  
  <xacro:call macro="arm_base" arm_name="1" reflect="1" />
  <xacro:call macro="arm_base" arm_name="2" reflect="-1" />
  <xacro:call macro="arm" arm_name="1"/>
  <xacro:call macro="arm" arm_name="2"/>

</robot>
