andrzej:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_1_joint_1_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_1_joint_1

  arm_1_joint_2_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_1_joint_2

  arm_1_joint_3_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_1_joint_3

  arm_1_joint_4_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_1_joint_4

  arm_1_joint_5_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_1_joint_5

  arm_2_joint_1_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_2_joint_1

  arm_2_joint_2_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_2_joint_2

  arm_2_joint_3_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_2_joint_3

  arm_2_joint_4_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_2_joint_4

  arm_2_joint_5_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_2_joint_5
