arm_1_joint_1_servo:
  channel: 1
  offset: 432
  direction: -1

arm_1_joint_2_servo:
  channel: 2
  offset: 262
  direction: 1

arm_1_joint_3_servo:
  channel: 3
  offset: 190
  direction: 1

arm_1_joint_4_servo:
  channel: 4
  offset: 319
  direction: 1

arm_1_joint_5_servo:
  channel: 5
  offset: 367
  direction: -1

arm_1_gripper_servo:
  channel: 6
  offset: 200
  direction: 1


arm_2_joint_1_servo:
  channel: 7
  offset: 187
  direction: 1

arm_2_joint_2_servo:
  channel: 8
  offset: 400
  direction: -1

arm_2_joint_3_servo:
  channel: 9
  offset: 427
  direction: -1

arm_2_joint_4_servo:
  channel: 10
  offset: 300
  direction: 1

arm_2_joint_5_servo:
  channel: 11
  offset: 400
  direction: -1

arm_2_gripper_servo:
  channel: 12
  offset: 300
  direction: 1


head_pan_joint_servo:
  channel: 13
  offset: 350
  direction: -1

head_tilt_joint_servo:
  channel: 14
  offset: 362
  direction: -1
